# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Vagrant Configuratie Bestand voor Ubuntu/Docker (VMWare Workstation/VirtualBox) en Windows 10 Enterprise
# Gemaakt door John Tutert
# Datum 25 juni 2023
#
# https://www.thisprogrammingthing.com/20s15/multiple-vagrant-vms-in-one-vagrantfile/
#
Vagrant.configure("2") do |config|
  # Ubuntu 22.10 met Docker en Docker Compose VMWare Workstation
  config.vm.define "wdckr" do |wdckr|
    wdckr.vm.box = "generic/ubuntu2210"
    wdckr.vm.hostname = "ulx-dkr-001"
    wdckr.vm.box_check_update = true
    wdckr.vm.provider "vmware_desktop" do |vmw|
      vmw.gui = true
      vmw.cpus = "2"
	  vmw.memory = "4096"
    end
    wdckr.vm.provision "shell", inline: <<-SHELL
     # Bijwerken Ubuntu 22.10   
     sudo apt-get update
     sudo apt-get upgrade -y
     # Midnight Commander en Screenfetch
     sudo apt-get install -y mc screenfetch
     # Docker en Docker Compose zoals beschreven op https://docs.docker.com/engine/install/ubuntu/
     sudo apt-get install -y ca-certificates curl gnupg
     sudo install -m 0755 -d /etc/apt/keyrings
     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
     sudo chmod a+r /etc/apt/keyrings/docker.gpg
     echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
     sudo apt-get update
     sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    SHELL
  end
  # Ubuntu 22.10 met Docker en Docker Compose VirtualBox
  config.vm.define "vdckr" do |vdckr|
    vdckr.vm.box = "generic/ubuntu2210"
    vdckr.vm.hostname = "ulx-dkr-001"
    vdckr.vm.box_check_update = true
    vdckr.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.cpus = "2"
	  vb.memory = "4096"
    end
    vdckr.vm.provision "shell", inline: <<-SHELL
     # Bijwerken Ubuntu 22.10   
     sudo apt-get update
     sudo apt-get upgrade -y
     # Midnight Commander en Screenfetch
     sudo apt-get install -y mc screenfetch
     # Docker en Docker Compose zoals beschreven op https://docs.docker.com/engine/install/ubuntu/
     sudo apt-get install -y ca-certificates curl gnupg
     sudo install -m 0755 -d /etc/apt/keyrings
     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
     sudo chmod a+r /etc/apt/keyrings/docker.gpg
     echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
     sudo apt-get update
     sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    SHELL
  end
  # Windows 10 Enterprise 22H2 
  config.vm.define "wintien" do |wintien|
    wintien.vm.box = "gusztavvargadr/windows-10"
	wintien.vm.box_check_update = true
	wintien.vm.guest = :windows
	wintien.vm.boot_timeout = 3600
    wintien.vm.hostname = "WinTien"
	wintien.vm.communicator = "winrm"
	# wintien.vm.network "forwarded_port", guest: 3389, host: 3389, id: "rdp", auto_correct: true
    # wintien.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
    # wintien.winrm.host = "localhost"
    wintien.vm.provider "vmware_desktop" do |vb|
      vb.gui = true
      vb.cpus = "2"
	  vb.memory = "4096"
    end
   # wintien.vm.provision "shell", inline: <<-SHELL 
    wintien.vm.provision "shell", privileged: "true", inline: <<-SHELL
	 echo $ErrorActionPreference = 'Stop' >ps-winget.ps1
	 echo $r = Invoke-RestMethod -Method Get -Uri https://api.github.com/repos/microsoft/winget-cli/releases/latest >>ps-winget.ps1
	 echo $r.assets | ? { $_.name -match "\.msixbundle$" } | % { >>ps-winget.ps1
	 echo     $downloadedFile = Join-Path $env:Temp $_.name >>ps-winget.ps1
	 echo     if (Test-Path $downloadedFile) { >>ps-winget.ps1
	 echo         Remove-Item $downloadedFile -Force >>ps-winget.ps1
	 echo  } >>ps-winget.ps1
	 REM powershell -ExecutionPolicy Unrestricted 
	 REM powershell -file ps-winget.ps1
    SHELL
  end
end