# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Vagrant Configuratie Bestand voor UBUNTU 22.10 VM binnen VMware Workstation PRO
# Gemaakt door John Tutert
#
Vagrant.configure("2") do |config|
  config.vm.define "dckr" do |dckr|
    dckr.vm.box = "generic/ubuntu2210"
    dckr.vm.hostname = "ulx-dkr-001"
    dckr.vm.box_check_update = true
    dckr.vm.provider "vmware_desktop" do |vb|
      vb.gui = true
      vb.cpus = "2"
	  vb.memory = "4096"
    end
    dckr.vm.provision "shell", inline: <<-SHELL
     # Bijwerken Ubuntu 22.10   
     sudo apt-get update
     sudo apt-get upgrade -y
     # Midnight Commander en Screenfetch
     sudo apt-get install -y mc screenfetch
     # Docker en Docker Compose zoals beschreven op https://docs.docker.com/engine/install/ubuntu/
     sudo apt-get install -y ca-certificates curl gnupg
     sudo install -m 0755 -d /etc/apt/keyrings
     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
     sudo chmod a+r /etc/apt/keyrings/docker.gpg
     echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
     sudo apt-get update
     sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    SHELL
  end
end